## Tensorflow - Numpy Equivalence

Exercises in **Refresher_numpy** are repeated for **tensorflow** version

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.Session()

In [4]:
const = tf.constant(10)
sess.run(const)

10

### Generating sequence

In [7]:
arange = tf.range(0,10,1)
print(arange)
print(arange.op)

Tensor("range_2:0", shape=(10,), dtype=int32)
name: "range_2"
op: "Range"
input: "range_2/start"
input: "range_2/limit"
input: "range_2/delta"
attr {
  key: "Tidx"
  value {
    type: DT_INT32
  }
}



In [8]:
sess.run(arange)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [11]:
linspace = tf.linspace(0.,10.,10) #start stop must be float
print(linspace.op)

name: "LinSpace_2"
op: "LinSpace"
input: "LinSpace_2/start"
input: "LinSpace_2/stop"
input: "LinSpace_2/num"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "Tidx"
  value {
    type: DT_INT32
  }
}



In [13]:
sess.run(linspace)

array([ 0.       ,  1.1111112,  2.2222223,  3.3333335,  4.4444447,
        5.555556 ,  6.666667 ,  7.777778 ,  8.888889 , 10.       ],
      dtype=float32)

### Tensor creation

In [14]:
zeros = tf.zeros((3,5)) #or tf.ones
print(zeros.op)

name: "zeros"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
        dim {
          size: 3
        }
        dim {
          size: 5
        }
      }
      float_val: 0.0
    }
  }
}



In [15]:
sess.run(zeros)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [26]:
fill = tf.fill((3,5),4)
print(fill.op)
sess.run(fill)

name: "Fill_2"
op: "Fill"
input: "Fill_2/dims"
input: "Fill_2/value"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}
attr {
  key: "index_type"
  value {
    type: DT_INT32
  }
}



array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]], dtype=int32)

In [27]:
fill_const = tf.constant(4,shape=(3,5))
print(fill_const.op)
sess.run(fill_const)

name: "Const_2"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
        dim {
          size: 3
        }
        dim {
          size: 5
        }
      }
      int_val: 4
    }
  }
}



array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]], dtype=int32)

In [16]:
rnd_normal = tf.random_normal((3,5),1,0.01)
print(rnd_normal.op)

name: "random_normal"
op: "Add"
input: "random_normal/mul"
input: "random_normal/mean"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}



In [17]:
sess.run(rnd_normal)

array([[0.9995551 , 0.99447954, 0.98896337, 1.0143579 , 1.004673  ],
       [0.9862911 , 1.003186  , 1.0032037 , 0.9918547 , 1.0023279 ],
       [1.0119741 , 1.0049429 , 1.0007715 , 0.99658316, 0.99718565]],
      dtype=float32)

**Using random seed**

In [89]:
tf.set_random_seed(99)

In [40]:
rnd_int = tf.random_uniform((3,5),0,10,dtype=tf.int32,seed=101)
sess.run(rnd_int)

array([[3, 5, 1, 3, 3],
       [0, 6, 8, 4, 1],
       [2, 4, 7, 9, 5]], dtype=int32)

### Reshaping

Everything works same as numpy

In [43]:
const = tf.range(0,15,1)
sess.run(const)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int32)

In [46]:
reshape = tf.reshape(const,(3,5)) 
print(reshape)
sess.run(reshape)

Tensor("Reshape_7:0", shape=(3, 5), dtype=int32)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]], dtype=int32)

In [47]:
reshape = tf.reshape(reshape,(-1,)) #dont miss the comma
print(reshape)
sess.run(reshape)

Tensor("Reshape_8:0", shape=(15,), dtype=int32)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int32)

In [48]:
reshape = tf.reshape(reshape,(5,-1))
print(reshape)
sess.run(reshape)

Tensor("Reshape_9:0", shape=(5, 3), dtype=int32)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]], dtype=int32)

### Tensor operations

In [52]:
max_v = tf.reduce_max(const)
sess.run(max_v)

14

In [53]:
min_v = tf.reduce_min(const)
sess.run(min_v)

0

In [54]:
mean_v = tf.reduce_mean(const)
sess.run(mean_v)

7

In [56]:
#Index location of max value
argmax_v = tf.argmax(const)
sess.run(argmax_v)

14

### Slicing

Everything including syntax works same as numpy

In [57]:
mat = tf.reshape(tf.range(0,100,1),(10,10))
sess.run(mat)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]], dtype=int32)

In [58]:
sess.run(mat[0,:])#First row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [59]:
sess.run(mat[:,0])#First column

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=int32)

In [60]:
sess.run(mat[:2,:3]) #slice first 2 rows and 3 columns

array([[ 0,  1,  2],
       [10, 11, 12]], dtype=int32)

In [62]:
sess.run(mat[2:4,5:-2]) #slice from 2nd until 4th row, from 5th until last second column

array([[25, 26, 27],
       [35, 36, 37]], dtype=int32)

In [63]:
sess.run(mat[:5:2,:5:2]) #slice every 2nd element from first 5 rows and column 

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]], dtype=int32)

In [65]:
sess.run(mat[::2,::2])#slice every 2nd element in whole matrix

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]], dtype=int32)

In [66]:
sess.run(mat[2::2,3::2]) #every 2nd element starting from index 2 of row and index 3 of column

array([[23, 25, 27, 29],
       [43, 45, 47, 49],
       [63, 65, 67, 69],
       [83, 85, 87, 89]], dtype=int32)

In [67]:
sess.run(mat[::-1,::-1]) #reverse the entire matrix

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]], dtype=int32)

In [68]:
sess.run(mat[3::-1,3::-1]) #pick up the first 3 rows and column and reverse them

array([[33, 32, 31, 30],
       [23, 22, 21, 20],
       [13, 12, 11, 10],
       [ 3,  2,  1,  0]], dtype=int32)

### Masking

**tf.boolean_mask** should be used

In [70]:
my_filter = mat > 50
print(my_filter)
sess.run(my_filter)

Tensor("Greater_1:0", shape=(10, 10), dtype=bool)


array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [75]:
sess.run(tf.boolean_mask(mat,mat>50)) #Equivalent to mat[mat>50] ==> mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int32)

### Broadcasting

Works same as numpy

In [76]:
arr = tf.ones((5,4))
sess.run(arr)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [77]:
sess.run(arr + 1) #(5,4) + (1,)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)

In [78]:
sess.run(arr + [1,2,3,4]) #(5,4) + (4,)

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]], dtype=float32)

In [82]:
sess.run(arr + tf.reshape(tf.constant([1.,2.,3.,4.,5.]),(5,1)))#(5,4) + (5,1)

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]], dtype=float32)

### Concatenation

In [86]:
features = tf.random_uniform((10,3),0,101,dtype=tf.int32)
labels = tf.random_uniform((10,1),0,2,dtype=tf.int32)
print(features)
print(labels)

Tensor("random_uniform_10:0", shape=(10, 3), dtype=int32)
Tensor("random_uniform_11:0", shape=(10, 1), dtype=int32)


In [87]:
sess.run(tf.concat([features,labels],axis=1)) #same syntax as numpy

array([[ 0, 35, 82,  0],
       [65, 26,  5,  0],
       [51, 19, 87,  0],
       [94, 75, 41,  1],
       [ 4, 18, 60,  0],
       [82, 16, 14,  0],
       [97, 51, 67,  0],
       [11, 82, 85,  1],
       [ 4, 30, 76,  0],
       [16, 86, 82,  1]], dtype=int32)

In [88]:
sess.close()